<?php
$destPosts = array_values(array_filter($posts, fn($p) => in_array('Destination eSIM', $p['categories'] ?? [], true)));
if (empty($destPosts)) { $destPosts = $posts; }
$featured = array_slice($destPosts, 0, 4);
ob_start();
?>
<section class="hero"><div class="hero-inner"><div><p class="eyebrow"><?= htmlspecialchars($config['hero_badge']) ?></p><h1><?= htmlspecialchars($config['hero_title']) ?></h1><p class="lead"><?= htmlspecialchars($config['hero_subtitle']) ?></p><div class="searchbox"><input id="search" placeholder="Où partez-vous ? Maroc, Japon, USA…"><a class="btn" href="/destinations/">Comparer</a></div><div class="proof"><?php foreach (($config['hero_stats'] ?? []) as $stat): ?><span class="pill"><?= htmlspecialchars($stat) ?></span><?php endforeach; ?></div></div><aside class="phone"><p>Top offres observées</p><h2>eSIM voyage</h2><?php foreach ($featured as $p): ?><div class="app-row"><span><?= htmlspecialchars($p['meta']['flag'] ?? '🌍') ?> <?= htmlspecialchars(str_replace('eSIM ', '', $p['title'])) ?></span><strong><?= htmlspecialchars($p['meta']['from_price'] ?? 'Comparer') ?></strong></div><?php endforeach; ?></aside></div></section>
<section class="section"><div class="section-head"><div><p class="eyebrow">Destinations populaires</p><h2>Comparez par pays ou région</h2></div><p>Chaque page destination affiche les forfaits, fournisseurs, prix d’appel, conseils de data et points de vigilance.</p></div><div class="grid" id="countryGrid"><?php foreach ($destPosts as $post): ?><article class="post-card" data-search="<?= htmlspecialchars(strtolower($post['title'] . ' ' . ($post['meta']['region'] ?? ''))) ?>"><div class="post-card__flag"><?= htmlspecialchars($post['meta']['flag'] ?? '🌍') ?></div><div class="post-meta"><span class="tag"><?= htmlspecialchars($post['meta']['region'] ?? 'Destination') ?></span><span class="tag"><?= htmlspecialchars($post['meta']['offers_count'] ?? '') ?> offres</span></div><h2><a href="/<?= htmlspecialchars($post['slug']) ?>/"><?= htmlspecialchars($post['title']) ?></a></h2><p><?= htmlspecialchars($post['excerpt']) ?></p><a class="read-more" href="/<?= htmlspecialchars($post['slug']) ?>/">Comparer →</a></article><?php endforeach; ?></div></section>
<section class="section split"><div><p class="eyebrow">Fournisseurs</p><h2>Comparer Saily, Airalo, GigSky, Holafly, Ubigi…</h2><p class="lead">Le meilleur choix dépend moins de la marque que du pays, du volume, de la durée et de la politique hotspot.</p></div><div class="providers"><article class="provider"><h3>Saily</h3><p>Application très simple, prix d’appel bas, marque Nord Security.</p></article><article class="provider"><h3>Airalo</h3><p>Catalogue massif, offres locales et régionales très populaires.</p></article><article class="provider"><h3>GigSky</h3><p>Essais gratuits sur certaines destinations et bonne couverture 5G.</p></article><article class="provider"><h3>Holafly</h3><p>Data illimitée lisible pour gros consommateurs.</p></article></div></section>
<section class="section"><div class="guide-box"><p class="eyebrow">Mode d’emploi</p><h2>Connecté en 3 étapes</h2><ol><li>Choisissez votre destination et estimez la data utile.</li><li>Comparez prix, durée, réseau local et hotspot.</li><li>Installez l’eSIM avant le départ, puis activez la data à l’arrivée.</li></ol></div></section>
<script>const s=document.getElementById('search'); if(s) s.addEventListener('input',()=>{const q=s.value.toLowerCase();document.querySelectorAll('[data-search]').forEach(c=>c.style.display=c.dataset.search.includes(q)?'':'none')});</script>
<?php $mainContent = ob_get_clean(); require __DIR__ . '/layout.php'; ?>
