import fs from 'fs';
import path from 'path';
const root = process.cwd();
const dist = path.join(root, 'dist');
fs.rmSync(dist, {recursive:true, force:true});
fs.mkdirSync(dist, {recursive:true});
const destinations = JSON.parse(fs.readFileSync('data/destinations.json','utf8'));
const providers = JSON.parse(fs.readFileSync('data/providers.json','utf8'));
const css = fs.readFileSync('src/styles.css','utf8');
const esc = s => String(s).replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const offerUrl = d => `https://www.meilleure-esim.fr/pays/${d.slug}`;
function layout({title, description, canonical, body, schema=''}){
 return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${canonical}"><meta name="theme-color" content="#072b2f"><style>${css}</style>${schema}</head><body><header class="nav"><a class="brand" href="/"><span>✈️</span> Comparateur eSIM</a><nav><a href="/#destinations">Destinations</a><a href="/#fournisseurs">Fournisseurs</a><a href="/#guide">Guide</a></nav></header>${body}<footer><div><strong>Comparateur eSIM</strong><p>Données de marché consolidées depuis des pages publiques de fournisseurs/comparateurs, à revérifier avant achat. Dernière compilation : juillet 2026.</p></div><a href="/sitemap.xml">Sitemap</a></footer></body></html>`
}
function offerRows(d, limit=99){ return d.offers.slice(0,limit).map((o,i)=>`<tr><td><strong>${esc(o.provider)}</strong><span class="badge">${esc(o.badge)}</span></td><td>${esc(o.plan)}</td><td>${esc(o.data)}</td><td>${esc(o.duration)}</td><td><strong>${esc(o.price)}</strong></td><td>${esc(o.network)}</td><td><a class="mini" rel="nofollow sponsored" href="${offerUrl(d)}">Voir</a></td></tr>`).join('') }
function cards(){ return destinations.map(d=>`<a class="country-card" href="/${d.slug}/" data-search="${esc((d.name+' '+d.region).toLowerCase())}"><span>${d.flag}</span><strong>${esc(d.name)}</strong><small>${esc(d.region)}</small><em>${d.count}+ offres · dès ${esc(d.from)}</em></a>`).join('') }
function index(){
 const top = destinations.slice(0,4).map(d=>`<article class="deal"><div><span class="flag">${d.flag}</span><h3>eSIM ${esc(d.name)}</h3><p>${d.count}+ forfaits comparés · meilleur choix : ${esc(d.best)}</p></div><strong>${esc(d.from)}</strong><a class="mini" href="/${d.slug}/">Comparer</a></article>`).join('')
 const body = `<main><section class="hero"><div class="hero-copy"><p class="eyebrow">Comparateur indépendant · données eSIM voyage</p><h1>Trouvez la meilleure eSIM pour voyager sans hors forfait</h1><p class="lead">Comparez fournisseurs, data, durée, couverture et prix pour choisir une eSIM avant le départ. Interface rapide inspirée des meilleures apps voyage : recherche destination, cartes lisibles, CTA directs.</p><div class="searchbox"><input id="search" placeholder="Où partez-vous ? Maroc, Japon, USA…" autocomplete="off"><button onclick="document.getElementById('destinations').scrollIntoView()">Comparer</button></div><div class="proof"><span>198+ destinations suivies</span><span>5+ fournisseurs</span><span>26k+ forfaits marché</span></div></div><div class="phone"><div class="phone-top"></div><h2>eSIM ${destinations[0].name}</h2><p>Dès ${destinations[0].from}</p>${destinations[0].offers.slice(0,3).map(o=>`<div class="app-row"><span>${esc(o.provider)}</span><strong>${esc(o.price)}</strong></div>`).join('')}</div></section><section class="section"><h2>Meilleurs deals du moment</h2><div class="deals">${top}</div></section><section class="section" id="destinations"><div class="section-head"><div><p class="eyebrow">Destinations populaires</p><h2>Comparez par pays ou région</h2></div><p>Données issues de pages publiques, avec redirection vers la page source pour achat/vérification finale.</p></div><div class="grid" id="countryGrid">${cards()}</div></section><section class="section split" id="fournisseurs"><div><p class="eyebrow">Fournisseurs eSIM</p><h2>Qui choisir ?</h2><p>Le meilleur fournisseur dépend surtout du volume nécessaire, de la durée et de la couverture locale. Voici la synthèse opérationnelle.</p></div><div class="providers">${providers.map(p=>`<article><h3>${esc(p.name)}</h3><p><strong>${esc(p.rating)}</strong> — ${esc(p.strength)}</p><small>${esc(p.bestFor)}</small></article>`).join('')}</div></section><section class="section guide" id="guide"><p class="eyebrow">Mode d’emploi</p><h2>Connecté en 3 étapes</h2><ol><li><strong>Choisissez la destination</strong> et estimez votre data : 1 Go/jour pour GPS + messages, plus si vidéo/hotspot.</li><li><strong>Comparez prix, durée, réseau et hotspot</strong>. Ne prenez pas seulement le prix le plus bas si vous partez hors grandes villes.</li><li><strong>Installez avant le départ</strong>, gardez votre SIM française pour SMS/appels, et basculez la data sur l’eSIM à l’arrivée.</li></ol></section></main><script>${fs.readFileSync('src/app.js','utf8')}</script>`
 return layout({title:'Comparateur eSIM : meilleures eSIM voyage dès 0,69 €', description:'Comparez les fournisseurs eSIM de voyage : Saily, Airalo, GigSky, Holafly, Ubigi, eSIM4Travel. Prix, data, durée et couverture par destination.', canonical:'https://comparateur-esim.fr/', body, schema:`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"WebSite",name:"Comparateur eSIM",url:"https://comparateur-esim.fr/",potentialAction:{"@type":"SearchAction",target:"https://comparateur-esim.fr/?q={search_term_string}","query-input":"required name=search_term_string"}})}</script>`})
}
function country(d){
 const faq = [{q:`Quelle eSIM choisir pour ${d.name} ?`,a:`Pour ${d.name}, commencez par comparer ${d.best}, Saily, Airalo, GigSky et eSIM4Travel selon le prix, la durée et le réseau. Le meilleur choix dépend de votre usage data et de votre itinéraire : ${d.hero}.`},{q:`Combien de data prévoir pour ${d.name} ?`,a:d.tips[0]},{q:`Quand installer son eSIM ${d.name} ?`,a:`Installez l’eSIM avant le départ sur Wi‑Fi. À l’arrivée, activez l’itinérance des données sur la ligne eSIM et conservez votre SIM habituelle pour appels/SMS.`}];
 const schema = `<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map(f=>({"@type":"Question",name:f.q,acceptedAnswer:{"@type":"Answer",text:f.a}}))})}</script>`
 const body = `<main><section class="country-hero"><a class="back" href="/">← Toutes les destinations</a><div><p class="eyebrow">${esc(d.region)}</p><h1>${d.flag} eSIM ${esc(d.name)} : comparez ${d.count}+ forfaits dès ${esc(d.from)}</h1><p class="lead">Sélection pratique pour ${esc(d.hero)}. Comparez les fournisseurs par prix, data, durée et réseau avant d’acheter.</p><a class="cta" rel="nofollow sponsored" href="${offerUrl(d)}">Voir toutes les offres vérifiées</a></div><aside><strong>Meilleur choix observé</strong><span>${esc(d.best)}</span><small>Source : meilleure-esim.fr, juillet 2026</small></aside></section><section class="section"><h2>Tableau comparatif eSIM ${esc(d.name)}</h2><div class="table-wrap"><table><thead><tr><th>Opérateur</th><th>Forfait</th><th>Data</th><th>Durée</th><th>Prix</th><th>Réseau</th><th></th></tr></thead><tbody>${offerRows(d)}</tbody></table></div></section><section class="section split"><div><p class="eyebrow">Conseil rapide</p><h2>Quel forfait choisir ?</h2></div><ul class="tips">${d.tips.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></section><section class="section faq"><h2>FAQ eSIM ${esc(d.name)}</h2>${faq.map(f=>`<details><summary>${esc(f.q)}</summary><p>${esc(f.a)}</p></details>`).join('')}</section></main>`
 return layout({title:`eSIM ${d.name} : comparatif forfaits, prix et fournisseurs`, description:`Comparez les forfaits eSIM pour ${d.name} : ${d.count}+ offres, dès ${d.from}, fournisseurs Saily, Airalo, GigSky, Holafly et autres.`, canonical:`https://comparateur-esim.fr/${d.slug}/`, body, schema})
}
fs.writeFileSync(path.join(dist,'index.html'), index());
for (const d of destinations){ const dir=path.join(dist,d.slug); fs.mkdirSync(dir,{recursive:true}); fs.writeFileSync(path.join(dir,'index.html'), country(d)); }
fs.writeFileSync(path.join(dist,'robots.txt'), 'User-agent: *\nAllow: /\nSitemap: https://comparateur-esim.fr/sitemap.xml\n');
const urls=['https://comparateur-esim.fr/',...destinations.map(d=>`https://comparateur-esim.fr/${d.slug}/`)];
fs.writeFileSync(path.join(dist,'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(u=>`  <url><loc>${u}</loc><changefreq>weekly</changefreq><priority>${u.endsWith('.fr/')?'1.0':'0.8'}</priority></url>`).join('\n')}\n</urlset>\n`);
fs.writeFileSync(path.join(dist,'404.html'), layout({title:'Page introuvable - Comparateur eSIM', description:'Page introuvable.', canonical:'https://comparateur-esim.fr/404.html', body:'<main><section class="section"><h1>Page introuvable</h1><p><a href="/">Retour au comparateur eSIM</a></p></section></main>'}));
console.log(`Build OK: ${urls.length} URLs`);
